### ISSUE TITLE
Is it real 0 dependencies?

### ISSUE THREAD

**Issue by suhanlee** [poksme/react-redux-immutable#2]
Hi, @poksme 

I am curious about `0 dependencies` meaning.
because your `react-redux-immutable` uses `immutable` library already.

Thank you~

**Comment by poksme** [comment]
Hello @suhanlee,

What _0 dependencies_ means in this context is that `react-redux-immutable` will not install any library and will use your existing dependencies.

To your point, it has declarative dependencies listed as `peerDependencies` over `immutable` `react`, `redux`, `react-redux`.

```js
  "peerDependencies": {
    "immutable": "^3.0.0",
    "react": "^0.14.0 || ^15.0.0-0 || ^16.0.0-0",
    "react-redux": "^5.0.0",
    "redux": "^2.0.0 || ^3.0.0 || ^4.0.0-0"
  },
```
